#!/bin/bash
#
# Simple command line application for Twitter.

. ./config.sh
. ./api.sh
. ./oauth.sh

get_timeline() {
  declare -A request_params

  local request_params
  local response

  request_params["method"]="GET"
  request_params["url"]="https://api.twitter.com/${api_version}/statuses/home_timeline.json"
  request_params["count"]=5

  response=$(api_request "$(declare -p request_params)")

  display_timeline "${response}"
}

display_timeline() {
  local i=0
  local yellow="\e[1;33m"
  local grey="\e[0;37m"
  local no_color="\e[0m"

  local response_length=$(echo "$1" | jq '. | length')

  for (( i=0; i<"${response_length}"; i++ )); do
    local name=$(echo "$1" | jq -r '.['${i}'] | .user.name')
    local screen_name=$(echo "$1" | jq -r '.['${i}'] | .user.screen_name')
    local text=$(echo "$1" | jq -r '.['${i}'] | .text')

    printf "${yellow}%s ${grey}@%s${no_color}\n" "${name}" "${screen_name}"
    echo -e "${text}\n"
  done
}

error_handler() {
  echo "$1" >&2
  exit 1
}

main() {
  config_load
  get_timeline
}

main
