#!/bin/bash
#
# Simple command line application for Twitter.

config_file=./.config

load_config()
{
  if [ -f "$config_file" ] && [ -r "$config_file" ]; then
    . $config_file
    check_config
  else
    error_handler "Config file not found"
  fi
}

check_config()
{
  if [ -z "$consumer_key" ]; then
    error_handler "Consumer key (API key) not found"
  elif [ -z "$consumer_secret" ]; then
    error_handler "Consumer secret (API secret) not found"
  elif [ -z "$access_token" ]; then
    error_handler "Access token not found"
  elif [ -z "$access_secret" ]; then
    error_handler "Access secret not found"
  fi
}

error_handler()
{
  echo "$1" >&2
  exit 1
}

load_config

printf "Access token: %s\n" $access_token
printf "Access secret: %s\n" $access_secret

exit
